### ISSUE TITLE
Install Task error

### ISSUE THREAD

**Issue by calebcartwright** [swellaby/azdo-shellcheck#28]
## Environment Details
* **ShellCheck Task**
    
  * [X] Install ShellCheck
    * Version: 0.0.17
  * [ ] Run ShellCheck
      * Version: 
* **Agent Type**
    
  * [X] Hosted Linux Agent
  * [ ] Hosted MacOS Agent
  * [ ] Hosted Windows Agent
  * [ ] Self-hosted/private Agent
* **Agent Tool Versions**
    
  * **Node.js Version**: 
  * **npm version**:

## Description

Install task is throwing an error due to missing deps (presumably a bundling/packaging issue)
```
## Log Output
##[section]Starting: Install ShellCheck
==============================================================================
Task         : Install ShellCheck
Description  : Installs Specified ShellCheck Version
Version      : 0.0.17
Author       : Swellaby
Help         : [More Information](https://github.com/swellaby/azdo-shellcheck)
==============================================================================
module.js:471
    throw err;
    ^

Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/vsts/work/_tasks/install-shellcheck_3f74db91-b37c-4602-bb92-2658c6d136f2/0.0.17/node_modules/azure-pipelines-task-lib/internal.js:10:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
##[error]Exit code 1 returned from process: file name '/home/vsts/agents/2.148.2/externals/node/bin/node', arguments '"/home/vsts/work/_tasks/install-shellcheck_3f74db91-b37c-4602-bb92-2658c6d136f2/0.0.17/runner.js"'.
##[section]Finishing: Install ShellCheck
```

**Comment by calebcartwright** [comment]
Closed in https://github.com/swellaby/azdo-shellcheck/commit/6f348d69a3c38e1f7d75b103e10a3c047968232a
